### ISSUE TITLE
Replace Openshift references with Metal3 where applicable

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/ironic-standalone-operator#12]
Ironic standalone operator is now a Metal3-io project, so replace OpenShift referencs with Metal3 where applicable.

**Comment by dtantsur** [comment]
The operator has never been an openshift project, so there is only one note in README as far as I can see.

**Comment by dtantsur** [comment]
And maybe https://github.com/metal3-io/ironic-standalone-operator/issues/7

**Comment by tuminoid** [comment]
Fair enough, it'll be an easy PR then :)

**Comment by tuminoid** [comment]
I think we can close this. The note in README still exists, but since Metal3 is used by OpenShift that might be relevant in future. Not worth of issue after #7 was closed.

/close
