### ISSUE TITLE
If I want to use this project to make a verification, How can i realize it?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#24]
I want to use this project to connect BMO , how can i realize it?

**Comment by dtantsur** [comment]
@matthewei hi! Please wait until this project is documented properly.

If you're ready to try something new and untested, you can create an Ironic resource, wait for it to become reconciled and ready, then use its cluster endpoint (`<name>.<namespace>.svc`) and its generated credentials when starting BMO.

/kind question

**Comment by matthewei** [comment]
> @matthewei hi! Please wait until this project is documented properly.
> 
> If you're ready to try something new and untested, you can create an Ironic resource, wait for it to become reconciled and ready, then use its cluster endpoint (`<name>.<namespace>.svc`) and its generated credentials when starting BMO.
> 
> /kind question

yes , I see.
