### ISSUE TITLE
Finish built-in deployment scripts

### ISSUE THREAD

**Issue by dtantsur** [metal3-io/ironic-standalone-operator#29]
Currently, [the deployment scripts](https://github.com/metal3-io/ironic-standalone-operator/tree/main/config) are an auto-generated mess. In particular, TLS support is commented out, preventing us from using webhooks. This all has to be cleaned up, TLS and webhook support enabled, redundant generated code removed.

**Comment by matthewei** [comment]
Please assign it to me!

**Comment by dtantsur** [comment]
I think you can use `/assign` to assign yourself.

/assign @matthewei
