### ISSUE TITLE
Error info isn't correct

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#34]
https://github.com/metal3-io/ironic-standalone-operator/blob/b24f9080bb33fa27d66c85885a16be826f5000ee/pkg/ironic/ironic.go#L146
I think `a distributed deployment` isn't correct and we can call `a distributed daemonset`

**Comment by dtantsur** [comment]
Here I'm using "deployment" in a wider sense, not in the sense of a Kubernetes resource. I think "distributed daemonset" may be confusing (and expose an implementation detailed), maybe "for distributed architecture"?

/triage accepted
/help

**Comment by matthewei** [comment]
> Here I'm using "deployment" in a wider sense, not in the sense of a Kubernetes resource. I think "distributed daemonset" may be confusing (and expose an implementation detailed), maybe "for distributed architecture"?
> 
> /triage accepted /help

yes, the `for distributed architecture` is better.
