### ISSUE TITLE
IronicStandalone really needs init-Pod(ipa-downloader)?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#40]
Some times we can build a http server out of cluster and we can also ues it to be as a image-server. And we can upload kernal and ramdisk into it. So I think we may don't need the init-Pod in Ironic's Pod.

**Comment by matthewei** [comment]
It is a  required option in our project. So I think we should provide users with a configurable item.

**Comment by dtantsur** [comment]
/triage accepted

I concur. We also don't use IPA-downloader in OpenShift. I'm not sure what the best API for that is, maybe as simple as a `cacheAgentImage` boolean flag.

**Comment by matthewei** [comment]
In fact I would like to update official-docs to tell user. You should get and upload IPA to the HTTP server. But if one want to use it. we can define a `acheAgentImage` boolean flag.

**Comment by matthewei** [comment]
@dtantsur could you assign it to me? I want to realize it.

**Comment by matthewei** [comment]
@dtantsur @Rozzii Hi friends, I  find we remove some ironc's configuration  https://github.com/metal3-io/ironic-standalone-operator/pull/47. If someone want to upgrade the ironic we have to modiry the controller's deployment. IMO we set image through controller's env isn't a good idea.

**Comment by matthewei** [comment]
As a controller, we should not intrude our code logic too much into CRD.

**Comment by dtantsur** [comment]
Hi! Could you open a new discussion here or on the public slack?

The removal was to follow the best practices of operators, as I got told several times by operator sdk folks.

**Comment by dtantsur** [comment]
> I find we remove some ironc's configuration https://github.com/metal3-io/ironic-standalone-operator/pull/47. If someone want to upgrade the ironic we have to modiry the controller's deployment.

Unrelated to the bug, but just as a heads-up: we're going to reconsider this decision based on https://github.com/metal3-io/ironic-standalone-operator/discussions/64. Please stay tuned.
