### ISSUE TITLE
Ironic-pod contains ironic-auth volume but doesn't use it

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#41]
![image](https://github.com/metal3-io/ironic-standalone-operator/assets/86186853/d86deac8-b71f-4e55-87f9-478882a4f49f)
Please check it.

**Comment by dtantsur** [comment]
It's actually used but only in the distributed case: https://github.com/metal3-io/ironic-standalone-operator/blob/main/pkg/ironic/containers.go#L242-L245 (for JSON RPC).

We will need its htpasswd part in all cases once there is some resolution for https://github.com/metal3-io/baremetal-operator/pull/1685

**Comment by Rozzii** [comment]
Just adding here the ironic-image related PR https://github.com/metal3-io/ironic-image/pull/506

**Comment by matthewei** [comment]
yes, I see.

**Comment by Rozzii** [comment]
@matthewei  can we close this issue?

**Comment by matthewei** [comment]
> @matthewei can we close this issue?

yes, why not
