### ISSUE TITLE
Do we need enable Dnsmaq's tftp? 

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ironic-standalone-operator#59]
Hi friends, I found that the dnsmasq has been enabled tftp. do we really need it?

```shell
interface=bond1
except-interface=lo
bind-dynamic
enable-tftp
tftp-root=/shared/tftpboot
log-queries

```

**Comment by dtantsur** [comment]
Yes. TFTP is needed to bootstrap iPXE because very few hardware models have iPXE built into them (if any at all, to be honest).
