### ISSUE TITLE
Add golangci-lint

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/ironic-standalone-operator#71]
Adding golangci-lint with as many linters enabled as possible is needed before releasing to ensure code quality.

As IRSO is using Golang 1.23, the required golangci-lint version is 1.60.1 or newer. Golangci-lint v1.60.x brings in new linters, so if/when adapting golangci-lint from BMO/CAPM3, the linter's allow list need to be checked to be up to date.

**Comment by elfosardo** [comment]
Just had some time and put together a quick PR for this
